name: password_credential
description: Access to Credential Management API Password Credential in Web, and Smartlock for Password in Android.
version: 0.3.5
homepage: https://github.com/irgaly/flutter_password_credential
publish_to: "none" 
environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.irgaly.password_credential
        pluginClass: PasswordCredentialPlugin
      web:
        pluginClass: PasswordCredentialPlugin
        fileName: src/password_credential_web.dart

